### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [glslio/glsl-transition-vignette-grid#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by gre** [comment]
There is a default license defined in the package.json.
But I can make a dedicated LICENSE file if you want

**Comment by karan** [comment]
That would help @gre. Thanks! :)

**Comment by gre** [comment]
I've updated the repository and release a new version that is now using **GPL v3**.

Hope this is fine to you.

Best regards :-)

**Comment by karan** [comment]
Thanks. You're awesome.
